import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { SupabaseClient } from "@supabase/supabase-js";

export type CustomerRecord={userId:string;name:string;email:string;phone:string;orders:number;spend:number;lastOrder:string};
type Voucher={id:number;title:string;active:boolean};
type AuditRow={id:number;admin_id:string|null;action_type:string;target_id:string|null;details_json:Record<string,unknown>;created_at:string};

export function CustomerManagement({client,customers,vouchers,onCustomerDeleted}:{client:SupabaseClient;customers:CustomerRecord[];vouchers:Voucher[];onCustomerDeleted:(id:string)=>void}){
  const [query,setQuery]=useState(""),[selectedId,setSelectedId]=useState(customers[0]?.userId??""),[kind,setKind]=useState<"voucher"|"points"|"stamps">("voucher"),[amount,setAmount]=useState(1),[voucherId,setVoucherId]=useState(vouchers.find(v=>v.active)?.id??0),[note,setNote]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[deleteOpen,setDeleteOpen]=useState(false),[confirmation,setConfirmation]=useState("");
  const visible=useMemo(()=>customers.filter(c=>`${c.name} ${c.email}`.toLowerCase().includes(query.toLowerCase())),[customers,query]);
  const selected=customers.find(c=>c.userId===selectedId)??visible[0]??null;
  useEffect(()=>{if(!selectedId&&customers[0])setSelectedId(customers[0].userId)},[customers,selectedId]);
  async function grant(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setMessage("");const {error}=await client.rpc("grant_customer_reward",{p_customer_id:selected.userId,p_reward_type:kind,p_amount:kind==="voucher"?null:amount,p_voucher_template_id:kind==="voucher"?voucherId:null,p_note:note});setMessage(error?error.message:`${kind[0].toUpperCase()+kind.slice(1)} granted to ${selected.name}.`);setBusy(false)}
  async function remove(){if(!selected||confirmation!==`DELETE ${selected.name}`)return;setBusy(true);setMessage("");const {data,error}=await client.functions.invoke("admin-control",{body:{action:"delete_customer",targetId:selected.userId}});if(error||data?.error)setMessage(data?.error??error?.message??"Deletion failed.");else{onCustomerDeleted(selected.userId);setDeleteOpen(false);setConfirmation("");setMessage("Customer account and associated data permanently deleted.")}setBusy(false)}
  return <div className="customer-admin-layout">
    <section className="panel customer-directory">
      <div className="control-heading"><div><h2>Customer directory</h2><p>{customers.length} registered customer accounts</p></div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or email" aria-label="Search customers"/></div>
      <div className="customer-account-list">{visible.length?visible.map(c=><button key={c.userId} className={selected?.userId===c.userId?"active":""} onClick={()=>setSelectedId(c.userId)}><span>{(c.name[0]||c.email[0]||"C").toUpperCase()}</span><b>{c.name}</b><small>{c.email||"Email unavailable"}</small><i>{c.orders} orders</i></button>):<p className="control-empty">No matching customers.</p>}</div>
    </section>
    {selected&&<div className="customer-control-detail">
      <section className="panel customer-summary"><div><span className="customer-avatar-large">{(selected.name[0]||"C").toUpperCase()}</span><div><h2>{selected.name}</h2><p>{selected.email}</p>{selected.phone&&<small>{selected.phone}</small>}</div></div><dl><div><dt>Orders</dt><dd>{selected.orders}</dd></div><div><dt>Lifetime spend</dt><dd>RM {selected.spend.toFixed(2)}</dd></div><div><dt>Last order</dt><dd>{selected.lastOrder||"—"}</dd></div></dl></section>
      <form className="panel reward-assignment" onSubmit={grant}><h2>Grant a reward</h2><p>Every manual adjustment is recorded in the Activity Log.</p>{message&&<div className={message.includes("granted")||message.includes("deleted")?"success":"error"} role="status">{message}</div>}<label>Reward type<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="voucher">Specific voucher</option><option value="points">Points credit</option><option value="stamps">Stamp credit</option></select></label>{kind==="voucher"?<label>Voucher<select value={voucherId} onChange={e=>setVoucherId(Number(e.target.value))}>{vouchers.filter(v=>v.active).map(v=><option value={v.id} key={v.id}>{v.title}</option>)}</select></label>:<label>{kind==="points"?"Points":"Stamps"}<input type="number" min="1" max={kind==="points"?1000000:1000} value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label>}<label>Internal note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={240} placeholder="Why is this adjustment being made?"/></label><button className="primary" disabled={busy||kind==="voucher"&&!voucherId}>{busy?"Working…":"Grant reward"}</button></form>
      <section className="panel account-danger"><h2>Delete customer account</h2><p>Permanently removes Auth access, orders, carts, profile and rewards. This cannot be undone.</p><button className="destructive" onClick={()=>setDeleteOpen(true)}>Delete customer</button></section>
    </div>}
    {deleteOpen&&selected&&<div className="admin-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDeleteOpen(false)}}><section className="admin-confirm-modal" role="dialog" aria-modal="true"><h2>Delete {selected.name}?</h2><p>This permanently deletes the customer and all associated operational data.</p><label>Type <strong>DELETE {selected.name}</strong><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoFocus/></label><div><button onClick={()=>setDeleteOpen(false)}>Cancel</button><button className="destructive" disabled={busy||confirmation!==`DELETE ${selected.name}`} onClick={remove}>{busy?"Deleting…":"Delete permanently"}</button></div></section></div>}
  </div>
}

export function ActivityLog({client}:{client:SupabaseClient}){
  const [rows,setRows]=useState<AuditRow[]>([]),[page,setPage]=useState(0),[action,setAction]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");const pageSize=25;
  useEffect(()=>{let live=true;(async()=>{setLoading(true);let q=client.from("admin_audit_logs").select("id,admin_id,action_type,target_id,details_json,created_at").order("created_at",{ascending:false}).range(page*pageSize,page*pageSize+pageSize-1);if(action)q=q.ilike("action_type",`%${action}%`);const {data,error}=await q;if(live){setRows((data??[]) as AuditRow[]);setError(error?.message??"");setLoading(false)}})();return()=>{live=false}},[client,page,action]);
  return <section className="panel audit-log"><div className="control-heading"><div><h2>Activity Log</h2><p>Immutable history of privileged administrator actions.</p></div><input value={action} onChange={e=>{setAction(e.target.value);setPage(0)}} placeholder="Filter by action" aria-label="Filter activity"/></div>{error&&<div className="error">{error}</div>}<div className="table-scroll"><table><thead><tr><th>When</th><th>Action</th><th>Administrator</th><th>Target</th><th>Details</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>Loading activity…</td></tr>:rows.length?rows.map(row=><tr key={row.id}><td>{new Date(row.created_at).toLocaleString()}</td><td><span className="audit-action">{row.action_type.replaceAll("."," · ")}</span></td><td><code>{row.admin_id?.slice(0,8)??"System"}</code></td><td><code>{row.target_id?.slice(0,12)??"—"}</code></td><td><details><summary>View</summary><pre>{JSON.stringify(row.details_json,null,2)}</pre></details></td></tr>):<tr><td colSpan={5}>No activity matches this filter.</td></tr>}</tbody></table></div><div className="audit-pagination"><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={rows.length<pageSize} onClick={()=>setPage(p=>p+1)}>Next</button></div></section>
}

const resetActions=[
  {id:"customers",title:"Wipe all customers",phrase:"WIPE CUSTOMERS",copy:"Deletes every non-team Auth account plus customer orders, carts, profiles and rewards."},
  {id:"products",title:"Wipe all products",phrase:"WIPE PRODUCTS",copy:"Deletes the master product catalog and all branch availability records."},
  {id:"stores_team",title:"Wipe stores & team",phrase:"WIPE STORES AND TEAM",copy:"Deletes branch orders, stores, and every team account except the signed-in owner."},
  {id:"factory",title:"Factory reset",phrase:"FACTORY RESET",copy:"Clears customers, catalog, stores, team, rewards and campaigns. The signed-in owner and audit trail remain for recovery."},
] as const;
export function DangerZone({client}:{client:SupabaseClient}){
  const [chosen,setChosen]=useState<(typeof resetActions)[number]|null>(null),[confirmation,setConfirmation]=useState(""),[stage,setStage]=useState<0|1>(0),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>{if(!chosen)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!busy){setChosen(null);setConfirmation("");setStage(0)}};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close)},[chosen,busy]);
  async function execute(){if(!chosen||confirmation!==chosen.phrase||stage!==1)return;setBusy(true);const {data,error}=await client.functions.invoke("admin-control",{body:{action:"system_reset",reset:chosen.id,confirmation}});setBusy(false);if(error||data?.error){setMessage(data?.error??error?.message??"Reset failed.");return}setMessage(`${chosen.title} completed. ${data.deletedAuthAccounts??0} Auth accounts removed.`);setChosen(null);setConfirmation("");setStage(0)}
  return <section className="danger-zone-page"><div className="danger-intro"><h2>System Reset</h2><p>These controls permanently destroy live business data. Export anything you need before continuing.</p></div><div className="reset-list">{resetActions.map(item=><article key={item.id}><div><h3>{item.title}</h3><p>{item.copy}</p></div><button className="destructive" onClick={()=>{setChosen(item);setStage(0);setConfirmation("");setMessage("")}}>Configure reset</button></article>)}</div>{message&&<div className={message.includes("completed")?"success":"error"} role="status">{message}</div>}{chosen&&<div className="admin-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy){setChosen(null);setConfirmation("");setStage(0)}}}><section className="admin-confirm-modal danger-confirm" role="dialog" aria-modal="true"><h2>{stage===0?"This cannot be undone":chosen.title}</h2>{stage===0?<><p>{chosen.copy}</p><p>Continue only if you understand that backups are your only recovery path.</p><div><button autoFocus onClick={()=>setChosen(null)}>Cancel</button><button className="destructive" onClick={()=>setStage(1)}>I understand, continue</button></div></>:<><label>Type <strong>{chosen.phrase}</strong> to confirm<input value={confirmation} onChange={e=>setConfirmation(e.target.value)} autoFocus/></label><div><button onClick={()=>setStage(0)}>Back</button><button className="destructive" disabled={busy||confirmation!==chosen.phrase} onClick={execute}>{busy?"Resetting…":"Permanently reset"}</button></div></>}</section></div>}</section>
}
