import Link from "next/link";
import { getCampaigns, getProducts, getPublishedPageByPath, getStores, orderUrl } from "@/lib/content";
import { PublishedPage } from "@/components/PublishedPage";

export default async function HomePage() {
  const [published,products,campaigns,stores]=await Promise.all([getPublishedPageByPath("/"),getProducts(),getCampaigns(),getStores()]);
  if(published) return <PublishedPage page={published}/>;
  return <main><section className="hero"><div className="hero-copy"><h1>Born in Sarawak.<br/><em>Brewed forward.</em></h1><p>Kopi Papa brings the strength of local kopi into a modern coffee experience, made for every generation.</p><div className="hero-actions"><a className="button gold" href={orderUrl}>Order for pickup</a><Link className="text-link" href="/story">Meet Kopi Papa</Link></div></div><div className="hero-stage" aria-label="Three signature Kopi Papa drinks"><span className="hero-orbit">Dad&apos;s Secret<br/>Sip of Tradition</span><img src="/assets/hero-drinks.png" alt="Double Soul, 3 Layer Kopi and Strawberry Matcha drinks"/></div><p className="hero-side">Kuching · Sarawak · Since 2023</p></section>
  <section className="intro-band" data-reveal><p>Strong “kaw” coffee, familiar local flavours and a new café ritual.</p><Link href="/menu">Explore the full menu</Link></section>
  <section className="product-theatre section" data-reveal><div className="section-heading"><h2>The cups people come back for.</h2><p>From the meeting point of kopitiam tradition and contemporary café culture.</p></div><div className="product-scroll">{products.slice(0,5).map((product,index)=><article className="showcase-product" key={product.id}><span>{String(index+1).padStart(2,"0")}</span><div className="product-image"><img src={product.image} alt={product.name}/></div><h3>{product.name}</h3><p>{product.description}</p></article>)}</div></section>
  <section className="double-soul" data-reveal><div className="double-image"><img src="/assets/about-counter.jpg" alt="Kopi Papa counter and team"/></div><div className="double-copy"><h2>Two coffee cultures.<br/>One Double Soul.</h2><p>Traditional local coffee and modern espresso meet in Kopi Papa&apos;s defining drink. It is a recipe built through months of testing and a belief that Sarawak coffee belongs in the future as proudly as it belongs in the past.</p><Link className="button navy" href="/story">Read our story</Link></div></section>
  <section className="sarawak-field section" data-reveal><div><h2>Gula apong.<br/>Kopi peng kaw.<br/>A Sarawak point of view.</h2><p>Local flavours are not an accent here. They are the starting point.</p></div><figure><img src="/assets/customer-cup.webp" alt="Customer holding a Kopi Papa drink outside the store"/><figcaption>A familiar cup, made for right now.</figcaption></figure></section>
  {campaigns.length>0&&<section className="campaign-strip section" data-reveal><div><h2>{campaigns[0].title}</h2><p>{campaigns[0].body}</p><a className="button gold" href={orderUrl}>See what&apos;s brewing</a></div><img src={campaigns[0].image} alt="Kopi Papa current campaign"/></section>}
  <section className="community section" data-reveal><div className="section-heading"><h2>Good coffee is a shared ritual.</h2><p>Made in Sarawak and carried into the everyday moments that keep a city moving.</p></div><div className="community-grid"><img src="/assets/customer-group.webp" alt="Customers enjoying Kopi Papa drinks"/><img src="/assets/store-kapit.webp" alt="Kopi Papa illuminated shop sign in Kapit"/><div><strong>{stores.length||"4+"}</strong><span>places to find your next cup</span><Link href="/stores">Find a store</Link></div></div></section>
  <section className="closing-cta" data-reveal><p>Your next cup is closer than you think.</p><h2>Pick it up.<br/>Carry the tradition.</h2><a className="button gold" href={orderUrl}>Start an order</a></section></main>;
}
