"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

const links = [["/", "Home"], ["/menu", "Menu"], ["/story", "Our Story"], ["/stores", "Stores"]] as const;
export function SiteHeader({ orderUrl }: { orderUrl:string }) { const path=usePathname(); const [open,setOpen]=useState(false); return <><header className="site-header"><Link className="site-brand" href="/" onClick={()=>setOpen(false)}><img src="/assets/kopi-papa-logo.png" alt="Kopi Papa"/><span><strong>Kopi Papa</strong><small>Dad&apos;s Secret, Sip of Tradition</small></span></Link><button className="menu-toggle" aria-label="Toggle navigation" aria-expanded={open} onClick={()=>setOpen(!open)}><span/><span/></button><nav className={open?"open":""} aria-label="Primary navigation">{links.map(([href,label])=><Link key={href} className={path===href?"active":""} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}<a className="nav-order" href={orderUrl}>Order Now</a></nav></header>{open&&<button className="nav-backdrop" type="button" aria-label="Close navigation" onClick={()=>setOpen(false)}/>}</> }
export function MotionInit(){const path=usePathname();useEffect(()=>{let observer:IntersectionObserver|undefined;const frame=requestAnimationFrame(()=>{const nodes=[...document.querySelectorAll<HTMLElement>("[data-reveal]")];if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){nodes.forEach(node=>node.dataset.visible="true");return}observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){(entry.target as HTMLElement).dataset.visible="true";observer?.unobserve(entry.target)}}),{threshold:.08,rootMargin:"0px 0px 4%"});nodes.forEach(node=>observer?.observe(node))});return()=>{cancelAnimationFrame(frame);observer?.disconnect()}},[path]);return null}
export function SiteFooter({orderUrl}:{orderUrl:string}){return <footer className="site-footer"><div><img src="/assets/kopi-papa-logo.png" alt=""/><div><strong>Born in Sarawak.</strong><p>Traditional roots. Modern coffee. One bold cup at a time.</p></div></div><nav>{links.slice(1).map(([href,label])=><Link key={href} href={href}>{label}</Link>)}<a href={orderUrl}>Order online</a></nav><small>© {new Date().getFullYear()} Kopi Papa. Demo website for brand presentation.</small></footer>}
