create table if not exists public.website_pages (
  id bigint generated by default as identity primary key,
  title text not null check (length(title) between 1 and 120),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  seo_title text not null default '' check (length(seo_title) <= 70),
  seo_description text not null default '' check (length(seo_description) <= 180),
  draft_content jsonb not null default '{"sections":[]}'::jsonb,
  published_content jsonb,
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (jsonb_typeof(draft_content) = 'object'),
  check (published_content is null or jsonb_typeof(published_content) = 'object')
);

create table if not exists public.website_page_versions (
  id bigint generated by default as identity primary key,
  page_id bigint not null references public.website_pages(id) on delete cascade,
  version_number integer not null,
  content jsonb not null check (jsonb_typeof(content) = 'object'),
  seo_title text not null default '',
  seo_description text not null default '',
  published_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(page_id,version_number)
);

create table if not exists public.website_redirects (
  id bigint generated by default as identity primary key,
  from_path text not null unique check (from_path like '/%'),
  to_path text not null check (to_path like '/%'),
  status_code integer not null default 308 check (status_code in (301,302,307,308)),
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (from_path <> to_path)
);

create table if not exists public.website_assets (
  id bigint generated by default as identity primary key,
  storage_path text not null unique,
  public_url text not null,
  file_name text not null,
  mime_type text not null check (mime_type like 'image/%'),
  width integer check (width is null or width > 0),
  height integer check (height is null or height > 0),
  alt_text text not null default '',
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists website_pages_published_idx
  on public.website_pages(slug) where published_content is not null;
create index if not exists website_page_versions_page_created_idx
  on public.website_page_versions(page_id,created_at desc);

alter table public.website_pages enable row level security;
alter table public.website_page_versions enable row level security;
alter table public.website_redirects enable row level security;
alter table public.website_assets enable row level security;

drop policy if exists public_reads_published_website_pages on public.website_pages;
create policy public_reads_published_website_pages on public.website_pages
  for select to anon,authenticated
  using (
    published_content is not null
    or exists (
      select 1 from public.staff s
      where s.user_id=(select auth.uid()) and s.active
        and s.role='global_admin'::public.admin_role
    )
  );

drop policy if exists global_admin_manages_website_pages on public.website_pages;
create policy global_admin_manages_website_pages on public.website_pages
  for all to authenticated
  using (exists (select 1 from public.staff s where s.user_id=(select auth.uid()) and s.active and s.role='global_admin'::public.admin_role))
  with check (exists (select 1 from public.staff s where s.user_id=(select auth.uid()) and s.active and s.role='global_admin'::public.admin_role));

drop policy if exists global_admin_reads_website_versions on public.website_page_versions;
create policy global_admin_reads_website_versions on public.website_page_versions
  for select to authenticated
  using (exists (select 1 from public.staff s where s.user_id=(select auth.uid()) and s.active and s.role='global_admin'::public.admin_role));

drop policy if exists global_admin_creates_website_versions on public.website_page_versions;
create policy global_admin_creates_website_versions on public.website_page_versions
  for insert to authenticated
  with check (exists (select 1 from public.staff s where s.user_id=(select auth.uid()) and s.active and s.role='global_admin'::public.admin_role));

drop policy if exists global_admin_manages_website_redirects on public.website_redirects;
create policy global_admin_manages_website_redirects on public.website_redirects
  for all to authenticated
  using (exists (select 1 from public.staff s where s.user_id=(select auth.uid()) and s.active and s.role='global_admin'::public.admin_role))
  with check (exists (select 1 from public.staff s where s.user_id=(select auth.uid()) and s.active and s.role='global_admin'::public.admin_role));

drop policy if exists public_reads_website_redirects on public.website_redirects;
create policy public_reads_website_redirects on public.website_redirects
  for select to anon,authenticated using (active);

drop policy if exists global_admin_manages_website_assets on public.website_assets;
create policy global_admin_manages_website_assets on public.website_assets
  for all to authenticated
  using (exists (select 1 from public.staff s where s.user_id=(select auth.uid()) and s.active and s.role='global_admin'::public.admin_role))
  with check (exists (select 1 from public.staff s where s.user_id=(select auth.uid()) and s.active and s.role='global_admin'::public.admin_role));

revoke all on public.website_pages,public.website_page_versions,public.website_redirects,public.website_assets from public,anon,authenticated;
grant select on public.website_pages,public.website_redirects to anon,authenticated;
grant insert,update,delete on public.website_pages,public.website_redirects,public.website_assets to authenticated;
grant select,insert on public.website_page_versions to authenticated;
grant select on public.website_assets to authenticated;
grant usage,select on sequence public.website_pages_id_seq,public.website_page_versions_id_seq,public.website_redirects_id_seq,public.website_assets_id_seq to authenticated;

create or replace function public.publish_website_page(p_page_id bigint)
returns jsonb language plpgsql security invoker set search_path=''
as $$
declare
  v_user uuid := (select auth.uid());
  v_page public.website_pages;
  v_version integer;
begin
  if v_user is null or not exists(
    select 1 from public.staff s
    where s.user_id=v_user and s.active and s.role='global_admin'::public.admin_role
  ) then raise exception 'Global administrator access required'; end if;

  select * into v_page from public.website_pages where id=p_page_id for update;
  if v_page.id is null then raise exception 'Website page not found'; end if;
  if jsonb_array_length(coalesce(v_page.draft_content->'sections','[]'::jsonb))=0 then
    raise exception 'Add at least one section before publishing';
  end if;

  select coalesce(max(version_number),0)+1 into v_version
  from public.website_page_versions where page_id=p_page_id;
  insert into public.website_page_versions(page_id,version_number,content,seo_title,seo_description,published_by)
  values(v_page.id,v_version,v_page.draft_content,v_page.seo_title,v_page.seo_description,v_user);
  update public.website_pages set published_content=draft_content,published_at=now(),updated_at=now(),updated_by=v_user
  where id=p_page_id;
  insert into public.admin_audit_logs(admin_id,action_type,target_id,details_json)
  values(v_user,'website.page_published',p_page_id::text,jsonb_build_object('slug',v_page.slug,'version',v_version));
  return jsonb_build_object('ok',true,'version',v_version,'slug',v_page.slug);
end $$;
revoke all on function public.publish_website_page(bigint) from public,anon;
grant execute on function public.publish_website_page(bigint) to authenticated;

create or replace function public.restore_website_page_version(p_version_id bigint)
returns jsonb language plpgsql security invoker set search_path=''
as $$
declare v_user uuid := (select auth.uid()); v_version public.website_page_versions;
begin
  if v_user is null or not exists(select 1 from public.staff s where s.user_id=v_user and s.active and s.role='global_admin'::public.admin_role)
    then raise exception 'Global administrator access required'; end if;
  select * into v_version from public.website_page_versions where id=p_version_id;
  if v_version.id is null then raise exception 'Website version not found'; end if;
  update public.website_pages set draft_content=v_version.content,seo_title=v_version.seo_title,
    seo_description=v_version.seo_description,updated_by=v_user,updated_at=now() where id=v_version.page_id;
  insert into public.admin_audit_logs(admin_id,action_type,target_id,details_json)
  values(v_user,'website.version_restored',v_version.page_id::text,jsonb_build_object('version_id',v_version.id,'version',v_version.version_number));
  return jsonb_build_object('ok',true,'page_id',v_version.page_id);
end $$;
revoke all on function public.restore_website_page_version(bigint) from public,anon;
grant execute on function public.restore_website_page_version(bigint) to authenticated;

notify pgrst,'reload schema';
