create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action_type text not null check (length(action_type) between 3 and 80),
  target_id text,
  details_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_logs_created_idx
  on public.admin_audit_logs(created_at desc);
create index if not exists admin_audit_logs_action_created_idx
  on public.admin_audit_logs(action_type,created_at desc);
create index if not exists admin_audit_logs_admin_created_idx
  on public.admin_audit_logs(admin_id,created_at desc);

alter table public.admin_audit_logs enable row level security;
drop policy if exists global_admin_reads_audit_logs on public.admin_audit_logs;
create policy global_admin_reads_audit_logs on public.admin_audit_logs
  for select to authenticated using (
    exists (
      select 1 from public.staff s
      where s.user_id=(select auth.uid()) and s.active
        and s.role='global_admin'::public.admin_role
    )
    and not coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false)
  );
revoke all on public.admin_audit_logs from public,anon,authenticated;
grant select on public.admin_audit_logs to authenticated;

create or replace function private.audit_admin_table_change()
returns trigger language plpgsql security definer set search_path=''
as $$
declare
  v_admin uuid := (select auth.uid());
  v_role public.admin_role;
  v_row jsonb := case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end;
begin
  if v_admin is null then if tg_op='DELETE' then return old; else return new; end if; end if;
  select s.role into v_role from public.staff s where s.user_id=v_admin and s.active limit 1;
  if v_role not in ('global_admin'::public.admin_role,'store_manager'::public.admin_role) then if tg_op='DELETE' then return old; else return new; end if; end if;
  insert into public.admin_audit_logs(admin_id,action_type,target_id,details_json)
    values(v_admin,lower(tg_table_name)||'.'||lower(tg_op),coalesce(v_row->>'id',v_row->>'user_id'),
      jsonb_build_object('table',tg_table_name,'operation',tg_op,'record',v_row));
  if tg_op='DELETE' then return old; else return new; end if;
end $$;
revoke all on function private.audit_admin_table_change() from public,anon,authenticated;

do $$
declare v_table text;
begin
  foreach v_table in array array['products','categories','stores','staff','campaigns','voucher_templates','reward_settings'] loop
    execute format('drop trigger if exists audit_admin_change on public.%I',v_table);
    execute format('create trigger audit_admin_change after insert or update or delete on public.%I for each row execute function private.audit_admin_table_change()',v_table);
  end loop;
end $$;

-- Historical analytics use a non-auth subject marker. Keeping user_id nullable
-- preserves the auth.users foreign key while allowing the real identity to be deleted.
alter table public.orders
  add column if not exists anonymized_customer_id uuid;
alter table public.reward_ledger
  add column if not exists anonymized_customer_id uuid;
alter table public.reward_ledger alter column user_id drop not null;
create index if not exists orders_anonymized_customer_idx
  on public.orders(anonymized_customer_id) where anonymized_customer_id is not null;

create or replace function private.grant_customer_reward_impl(
  p_customer_id uuid,
  p_reward_type text,
  p_amount integer default null,
  p_voucher_template_id bigint default null,
  p_note text default ''
) returns jsonb
language plpgsql security definer set search_path=''
as $$
declare
  v_admin uuid := (select auth.uid());
  v_voucher_id bigint;
begin
  if v_admin is null or coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false) then
    raise exception 'Verified administrator sign-in required';
  end if;
  if not exists(select 1 from public.staff s where s.user_id=v_admin and s.active and s.role='global_admin'::public.admin_role) then
    raise exception 'Global administrator access required';
  end if;
  if not exists(select 1 from auth.users u where u.id=p_customer_id) or
     exists(select 1 from public.staff s where s.user_id=p_customer_id) then
    raise exception 'Choose an active customer account';
  end if;

  if p_reward_type='points' then
    if coalesce(p_amount,0) <= 0 or p_amount > 1000000 then raise exception 'Points must be between 1 and 1,000,000'; end if;
    insert into public.reward_accounts(user_id,points_balance,stamp_count,lifetime_points,updated_at)
      values(p_customer_id,p_amount,0,p_amount,now())
      on conflict(user_id) do update set
        points_balance=public.reward_accounts.points_balance+excluded.points_balance,
        lifetime_points=public.reward_accounts.lifetime_points+excluded.lifetime_points,
        updated_at=now();
    insert into public.reward_ledger(user_id,entry_type,points_delta,stamps_delta,note)
      values(p_customer_id,'manual_adjustment',p_amount,0,left(coalesce(p_note,'Admin points grant'),240));
  elsif p_reward_type='stamps' then
    if coalesce(p_amount,0) <= 0 or p_amount > 1000 then raise exception 'Stamps must be between 1 and 1,000'; end if;
    insert into public.reward_accounts(user_id,points_balance,stamp_count,lifetime_points,updated_at)
      values(p_customer_id,0,p_amount,0,now())
      on conflict(user_id) do update set
        stamp_count=public.reward_accounts.stamp_count+excluded.stamp_count,
        updated_at=now();
    insert into public.reward_ledger(user_id,entry_type,points_delta,stamps_delta,note)
      values(p_customer_id,'manual_adjustment',0,p_amount,left(coalesce(p_note,'Admin stamp grant'),240));
  elsif p_reward_type='voucher' then
    if not exists(select 1 from public.voucher_templates v where v.id=p_voucher_template_id and v.active) then
      raise exception 'Choose an active voucher';
    end if;
    insert into public.user_vouchers(user_id,voucher_template_id,source,status,expires_at)
      select p_customer_id,v.id,'admin','active',v.expires_at
      from public.voucher_templates v where v.id=p_voucher_template_id
      returning id into v_voucher_id;
  else
    raise exception 'Reward type must be points, stamps, or voucher';
  end if;

  insert into public.admin_audit_logs(admin_id,action_type,target_id,details_json)
    values(v_admin,'customer.reward_granted',p_customer_id::text,
      jsonb_build_object('reward_type',p_reward_type,'amount',p_amount,
        'voucher_template_id',p_voucher_template_id,'voucher_id',v_voucher_id,'note',left(coalesce(p_note,''),240)));
  return jsonb_build_object('ok',true,'voucher_id',v_voucher_id);
end $$;

revoke all on function private.grant_customer_reward_impl(uuid,text,integer,bigint,text) from public,anon,authenticated;
grant execute on function private.grant_customer_reward_impl(uuid,text,integer,bigint,text) to authenticated;

create or replace function public.grant_customer_reward(
  p_customer_id uuid,
  p_reward_type text,
  p_amount integer default null,
  p_voucher_template_id bigint default null,
  p_note text default ''
) returns jsonb language plpgsql security invoker set search_path=''
as $$
begin
  if auth.uid() is null then raise exception 'Administrator sign-in required'; end if;
  return private.grant_customer_reward_impl(p_customer_id,p_reward_type,p_amount,p_voucher_template_id,p_note);
end $$;
revoke all on function public.grant_customer_reward(uuid,text,integer,bigint,text) from public,anon;
grant execute on function public.grant_customer_reward(uuid,text,integer,bigint,text) to authenticated;

create or replace function private.prepare_self_account_deletion_impl()
returns jsonb language plpgsql security definer set search_path=''
as $$
declare
  v_user uuid := (select auth.uid());
  v_deleted_subject constant uuid := '00000000-0000-0000-0000-000000000001'::uuid;
  v_orders integer := 0;
begin
  if v_user is null or coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false) then
    raise exception 'Verified customer sign-in required';
  end if;
  if exists(select 1 from public.staff s where s.user_id=v_user) or exists(select 1 from public.admin_users a where a.user_id=v_user) then
    raise exception 'Team accounts must be removed by another global administrator';
  end if;

  update public.orders set
    user_id=null,
    anonymized_customer_id=v_deleted_subject,
    customer_name='Deleted customer',
    customer_email=null
  where user_id=v_user;
  get diagnostics v_orders = row_count;

  update public.reward_ledger set user_id=null,anonymized_customer_id=v_deleted_subject where user_id=v_user;
  delete from public.customer_cart_items where user_id=v_user;
  delete from public.user_vouchers where user_id=v_user;
  delete from public.reward_accounts where user_id=v_user;
  delete from public.profiles where user_id=v_user;
  return jsonb_build_object('prepared',true,'orders_anonymized',v_orders);
end $$;
revoke all on function private.prepare_self_account_deletion_impl() from public,anon,authenticated;
grant execute on function private.prepare_self_account_deletion_impl() to authenticated;

create or replace function public.prepare_self_account_deletion()
returns jsonb language plpgsql security invoker set search_path=''
as $$
begin
  if auth.uid() is null then raise exception 'Customer sign-in required'; end if;
  return private.prepare_self_account_deletion_impl();
end $$;
revoke all on function public.prepare_self_account_deletion() from public,anon;
grant execute on function public.prepare_self_account_deletion() to authenticated;

notify pgrst,'reload schema';
