create table if not exists public.reward_settings (
  id boolean primary key default true check (id),
  active_system text not null default 'points' check (active_system in ('stamp','points')),
  points_per_rm integer not null default 10 check (points_per_rm > 0),
  stamp_threshold integer not null default 8 check (stamp_threshold between 2 and 50),
  stamp_reward_template_id bigint,
  updated_at timestamptz not null default now()
);

create table if not exists public.voucher_templates (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 100),
  description text not null default '',
  voucher_type text not null check (voucher_type in ('buy_x_free_one','free_drink','amount_off')),
  buy_quantity integer check (buy_quantity between 1 and 50),
  amount_off_cents integer check (amount_off_cents > 0),
  valid_scope text not null default 'any_drink' check (valid_scope in ('any_drink','category','product')),
  category_id bigint references public.categories(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  image_url text,
  expires_at timestamptz,
  point_cost integer check (point_cost is null or point_cost >= 0),
  available_in_shop boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((voucher_type <> 'buy_x_free_one') or buy_quantity is not null),
  check ((voucher_type <> 'amount_off') or amount_off_cents is not null),
  check ((valid_scope <> 'category') or category_id is not null),
  check ((valid_scope <> 'product') or product_id is not null)
);

alter table public.reward_settings drop constraint if exists reward_settings_stamp_reward_template_id_fkey;
alter table public.reward_settings add constraint reward_settings_stamp_reward_template_id_fkey foreign key (stamp_reward_template_id) references public.voucher_templates(id) on delete set null;
insert into public.reward_settings(id) values(true) on conflict(id) do nothing;

create table if not exists public.voucher_codes (
  id bigint generated by default as identity primary key,
  voucher_template_id bigint not null references public.voucher_templates(id) on delete cascade,
  code text not null unique check (code = upper(code) and code ~ '^[A-Z0-9]{6,24}$'),
  max_claims integer not null default 1 check (max_claims > 0),
  claim_count integer not null default 0 check (claim_count >= 0 and claim_count <= max_claims),
  expires_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.reward_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  points_balance integer not null default 0 check (points_balance >= 0),
  stamp_count integer not null default 0 check (stamp_count >= 0),
  lifetime_points integer not null default 0 check (lifetime_points >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.reward_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  order_id bigint references public.orders(id) on delete set null,
  entry_type text not null check (entry_type in ('points_earned','points_spent','stamps_earned','stamp_reward','manual_adjustment')),
  points_delta integer not null default 0,
  stamps_delta integer not null default 0,
  note text not null default '',
  created_at timestamptz not null default now()
);
create unique index if not exists reward_ledger_order_entry_key on public.reward_ledger(order_id,entry_type) where order_id is not null;
create index if not exists reward_ledger_user_created_idx on public.reward_ledger(user_id,created_at desc);
create index if not exists reward_settings_template_idx on public.reward_settings(stamp_reward_template_id);
create index if not exists voucher_templates_category_idx on public.voucher_templates(category_id);
create index if not exists voucher_templates_product_idx on public.voucher_templates(product_id);
create index if not exists voucher_codes_template_idx on public.voucher_codes(voucher_template_id);
create index if not exists user_vouchers_template_idx on public.user_vouchers(voucher_template_id);
create index if not exists user_vouchers_code_idx on public.user_vouchers(voucher_code_id);
create unique index if not exists user_vouchers_one_claim_per_code_idx on public.user_vouchers(user_id,voucher_code_id) where voucher_code_id is not null;
create index if not exists user_vouchers_order_idx on public.user_vouchers(order_id);

create table if not exists public.user_vouchers (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  voucher_template_id bigint not null references public.voucher_templates(id),
  voucher_code_id bigint references public.voucher_codes(id),
  source text not null check (source in ('secret_code','points_shop','stamp_reward','admin')),
  status text not null default 'active' check (status in ('active','used','expired')),
  claimed_at timestamptz not null default now(),
  used_at timestamptz,
  expires_at timestamptz,
  order_id bigint references public.orders(id) on delete set null,
  unique(user_id,voucher_code_id)
);
create index if not exists user_vouchers_user_status_idx on public.user_vouchers(user_id,status,claimed_at desc);

alter table public.reward_settings enable row level security;
alter table public.voucher_templates enable row level security;
alter table public.voucher_codes enable row level security;
alter table public.reward_accounts enable row level security;
alter table public.reward_ledger enable row level security;
alter table public.user_vouchers enable row level security;

create policy reward_settings_read on public.reward_settings for select to authenticated using (true);
create policy reward_settings_admin_write on public.reward_settings for all to authenticated using ((select private.current_staff_role())='global_admin') with check ((select private.current_staff_role())='global_admin');
create policy voucher_templates_member_read on public.voucher_templates for select to authenticated using (active or (select private.current_staff_role())='global_admin');
create policy voucher_templates_admin_write on public.voucher_templates for all to authenticated using ((select private.current_staff_role())='global_admin') with check ((select private.current_staff_role())='global_admin');
create policy voucher_codes_admin_read on public.voucher_codes for select to authenticated using ((select private.current_staff_role())='global_admin');
create policy voucher_codes_admin_write on public.voucher_codes for all to authenticated using ((select private.current_staff_role())='global_admin') with check ((select private.current_staff_role())='global_admin');
create policy reward_accounts_own_read on public.reward_accounts for select to authenticated using ((select auth.uid())=user_id or (select private.current_staff_role())='global_admin');
create policy reward_ledger_own_read on public.reward_ledger for select to authenticated using ((select auth.uid())=user_id or (select private.current_staff_role())='global_admin');
create policy user_vouchers_own_read on public.user_vouchers for select to authenticated using ((select auth.uid())=user_id or (select private.current_staff_role())='global_admin');
create policy user_vouchers_admin_update on public.user_vouchers for update to authenticated using ((select private.current_staff_role())='global_admin') with check ((select private.current_staff_role())='global_admin');

create or replace function private.award_completed_order_rewards() returns trigger language plpgsql security definer set search_path='' as $$
declare v_settings public.reward_settings%rowtype; v_points integer; v_stamps integer; v_rewards integer; v_template public.voucher_templates%rowtype;
begin
  if new.status <> 'completed' or old.status = 'completed' or new.user_id is null then return new; end if;
  if coalesce((select is_anonymous from auth.users where id=new.user_id),false) then return new; end if;
  select * into v_settings from public.reward_settings where id=true;
  insert into public.reward_accounts(user_id) values(new.user_id) on conflict(user_id) do nothing;
  if v_settings.active_system='points' then
    v_points=floor(new.total_cents::numeric*v_settings.points_per_rm/100)::integer;
    update public.reward_accounts set points_balance=points_balance+v_points,lifetime_points=lifetime_points+v_points,updated_at=now() where user_id=new.user_id;
    insert into public.reward_ledger(user_id,order_id,entry_type,points_delta,note) values(new.user_id,new.id,'points_earned',v_points,'Points from '||new.order_number) on conflict do nothing;
  else
    select coalesce(sum(quantity),0)::integer into v_stamps from public.order_items where order_id=new.id;
    update public.reward_accounts set stamp_count=stamp_count+v_stamps,updated_at=now() where user_id=new.user_id returning stamp_count/v_settings.stamp_threshold into v_rewards;
    insert into public.reward_ledger(user_id,order_id,entry_type,stamps_delta,note) values(new.user_id,new.id,'stamps_earned',v_stamps,'Stamps from '||new.order_number) on conflict do nothing;
    if v_rewards>0 and v_settings.stamp_reward_template_id is not null then
      select * into v_template from public.voucher_templates where id=v_settings.stamp_reward_template_id and active;
      if found then
        insert into public.user_vouchers(user_id,voucher_template_id,source,expires_at) select new.user_id,v_template.id,'stamp_reward',v_template.expires_at from generate_series(1,v_rewards);
        update public.reward_accounts set stamp_count=stamp_count-(v_rewards*v_settings.stamp_threshold) where user_id=new.user_id;
      end if;
    end if;
  end if;
  return new;
end $$;
drop trigger if exists award_completed_order_rewards on public.orders;
create trigger award_completed_order_rewards after update of status on public.orders for each row execute function private.award_completed_order_rewards();

create or replace function public.claim_voucher_code(p_code text) returns bigint language plpgsql security definer set search_path='' as $$
declare v_user uuid=(select auth.uid()); v_code public.voucher_codes%rowtype; v_template public.voucher_templates%rowtype; v_id bigint;
begin
  if v_user is null or coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false) then raise exception 'Sign in with an account to claim rewards.'; end if;
  select * into v_code from public.voucher_codes where code=upper(trim(p_code)) for update;
  if not found or not v_code.active or v_code.claim_count>=v_code.max_claims or (v_code.expires_at is not null and v_code.expires_at<=now()) then raise exception 'This code is invalid, expired, or already claimed.'; end if;
  if exists(select 1 from public.user_vouchers where user_id=v_user and voucher_code_id=v_code.id) then raise exception 'You have already claimed this code.'; end if;
  select * into v_template from public.voucher_templates where id=v_code.voucher_template_id and active and (expires_at is null or expires_at>now());
  if not found then raise exception 'This voucher is no longer available.'; end if;
  insert into public.user_vouchers(user_id,voucher_template_id,voucher_code_id,source,expires_at) values(v_user,v_template.id,v_code.id,'secret_code',coalesce(v_code.expires_at,v_template.expires_at)) returning id into v_id;
  update public.voucher_codes set claim_count=claim_count+1,active=(claim_count+1<max_claims) where id=v_code.id;
  return v_id;
end $$;

create or replace function public.purchase_reward(p_template_id bigint) returns bigint language plpgsql security definer set search_path='' as $$
declare v_user uuid=(select auth.uid()); v_template public.voucher_templates%rowtype; v_id bigint;
begin
  if v_user is null or coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false) then raise exception 'Sign in with an account to use rewards.'; end if;
  select * into v_template from public.voucher_templates where id=p_template_id and active and available_in_shop and point_cost is not null and (expires_at is null or expires_at>now()) for update;
  if not found then raise exception 'This reward is not available.'; end if;
  update public.reward_accounts set points_balance=points_balance-v_template.point_cost,updated_at=now() where user_id=v_user and points_balance>=v_template.point_cost;
  if not found then raise exception 'You do not have enough points.'; end if;
  insert into public.reward_ledger(user_id,entry_type,points_delta,note) values(v_user,'points_spent',-v_template.point_cost,'Purchased '||v_template.title);
  insert into public.user_vouchers(user_id,voucher_template_id,source,expires_at) values(v_user,v_template.id,'points_shop',v_template.expires_at) returning id into v_id;
  return v_id;
end $$;

create or replace function public.use_reward_voucher(p_user_voucher_id bigint) returns void language plpgsql security definer set search_path='' as $$
declare v_user uuid=(select auth.uid());
begin
  if v_user is null or coalesce(((select auth.jwt())->>'is_anonymous')::boolean,false) then
    raise exception 'Sign in with an account to use rewards.';
  end if;
  update public.user_vouchers
  set status='used',used_at=now()
  where id=p_user_voucher_id and user_id=v_user and status='active'
    and (expires_at is null or expires_at>now());
  if not found then raise exception 'This voucher is expired, used, or unavailable.'; end if;
end $$;

revoke all on function public.claim_voucher_code(text) from public,anon;
revoke all on function public.purchase_reward(bigint) from public,anon;
revoke all on function public.use_reward_voucher(bigint) from public,anon;
grant execute on function public.claim_voucher_code(text) to authenticated;
grant execute on function public.purchase_reward(bigint) to authenticated;
grant execute on function public.use_reward_voucher(bigint) to authenticated;

insert into public.voucher_templates(title,description,voucher_type,buy_quantity,valid_scope,image_url,expires_at,point_cost,available_in_shop,active)
select 'Papa Treat: Buy 2, Free 1','Buy two drinks and enjoy one selected drink free.','buy_x_free_one',2,'any_drink',(select image_url from public.products where image_url is not null order by sold desc nulls last limit 1),now()+interval '90 days',900,true,true
where not exists(select 1 from public.voucher_templates where title='Papa Treat: Buy 2, Free 1');
insert into public.voucher_templates(title,description,voucher_type,valid_scope,product_id,image_url,expires_at,point_cost,available_in_shop,active)
select 'Free Signature Drink','Enjoy one Signature drink on us.','free_drink','product',p.id,p.image_url,now()+interval '60 days',1200,true,true from public.products p where p.available order by p.sold desc nulls last,p.id limit 1
on conflict do nothing;
insert into public.voucher_templates(title,description,voucher_type,amount_off_cents,valid_scope,image_url,expires_at,point_cost,available_in_shop,active)
select 'RM3 Off Your Next Cup','Save RM3 on one qualifying order.','amount_off',300,'any_drink',(select image_url from public.products where image_url is not null order by id desc limit 1),now()+interval '45 days',350,true,true
where not exists(select 1 from public.voucher_templates where title='RM3 Off Your Next Cup');
insert into public.voucher_codes(voucher_template_id,code,max_claims,expires_at)
select id,'PAPAWELCOME',50,now()+interval '30 days' from public.voucher_templates where title='RM3 Off Your Next Cup' on conflict(code) do nothing;
insert into public.voucher_codes(voucher_template_id,code,max_claims,expires_at)
select id,'KOPIFREE',10,now()+interval '14 days' from public.voucher_templates where title='Free Signature Drink' on conflict(code) do nothing;
insert into public.voucher_codes(voucher_template_id,code,max_claims,expires_at)
select id,'PAPABUY2',25,now()+interval '30 days' from public.voucher_templates where title='Papa Treat: Buy 2, Free 1' on conflict(code) do nothing;
update public.reward_settings set stamp_reward_template_id=(select id from public.voucher_templates where title='Free Signature Drink' order by id limit 1) where id=true and stamp_reward_template_id is null;

alter publication supabase_realtime add table public.reward_settings;
alter publication supabase_realtime add table public.voucher_templates;
alter publication supabase_realtime add table public.reward_accounts;
alter publication supabase_realtime add table public.user_vouchers;
notify pgrst,'reload schema';
